[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "psycopg2-binary>=2.9.10",
    "python-nmap>=0.7.1",
    "sendgrid>=6.12.3",
    "sqlalchemy>=2.0.41",
]
